/**
 * Test Setup for crm-app Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities, fixtures, and database setup
 */

import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import Knex from 'knex';
import knexConfig from '../knexfile';

// Test database instance
let testDb: Knex.Knex;

// Test application instance
let testApp: NestFastifyApplication;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Knex.Knex> {
  if (!testDb) {
    testDb = Knex({
      client: 'better-sqlite3',
      connection: {
        filename: ':memory:',
      },
      useNullAsDefault: true,
      migrations: {
        directory: './migrations',
      },
      seeds: {
        directory: './seeds',
      },
    });

    // Run migrations
    await testDb.migrate.latest();
    // Run seeds (only if seed files exist)
    try {
      await testDb.seed.run();
    } catch (_e) {
      // Seeds may not exist, continue
    }
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    await testDb.destroy();
    testDb = undefined as any;
  }
}

/**
 * Create test application
 */
export async function createTestApp(module: any): Promise<NestFastifyApplication> {
  const moduleFixture: TestingModule = await Test.createTestingModule({
    imports: [module],
  }).compile();

  const app = moduleFixture.createNestApplication<NestFastifyApplication>(
    new FastifyAdapter()
  );

  await app.init();
  await app.getHttpAdapter().getInstance().ready();

  return app;
}

/**
 * Close test application
 */
export async function closeTestApp(app: NestFastifyApplication): Promise<void> {
  if (app) {
    await app.close();
  }
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories
 */
export const TestDataFactory = {
  /**
   * Create test Company data
   */
  createCompany(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: 'Test Name',
      industry: 'Test Industry',
      website: 'Test Website',
      phone: 'Test Phone',
      email: 'Test Email',
      employee_count: 1,
      annual_revenue: 10.99,
      status: 'Test Status',
      owner_id: 'Test Owner Id',
      ...overrides,
    };
  },

  /**
   * Create test Contact data
   */
  createContact(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      company_id: 'Test Company Id',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      email: 'Test Email',
      phone: 'Test Phone',
      mobile: 'Test Mobile',
      job_title: 'Test Job Title',
      department: 'Test Department',
      status: 'Test Status',
      lead_source: 'Test Lead Source',
      owner_id: 'Test Owner Id',
      ...overrides,
    };
  },

  /**
   * Create test Deal data
   */
  createDeal(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      company_id: 'Test Company Id',
      contact_id: 'Test Contact Id',
      name: 'Test Name',
      amount: 10.99,
      currency: 'Test Currency',
      stage: 'Test Stage',
      probability: 1,
      expected_close_date: '2024-01-15',
      actual_close_date: '2024-01-15',
      status: 'Test Status',
      description: 'Test text content',
      owner_id: 'Test Owner Id',
      ...overrides,
    };
  },

  /**
   * Create test DealStage data
   */
  createDealStage(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      pipeline_id: 'Test Pipeline Id',
      name: 'Test Name',
      sort_order: 1,
      default_probability: 1,
      is_won: true,
      is_lost: true,
      ...overrides,
    };
  },

  /**
   * Create test Pipeline data
   */
  createPipeline(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: 'Test Name',
      is_default: true,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Activity data
   */
  createActivity(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      activity_type: 'Test Activity Type',
      subject: 'Test Subject',
      description: 'Test text content',
      scheduled_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      duration_minutes: 1,
      status: 'Test Status',
      owner_id: 'Test Owner Id',
      ...overrides,
    };
  },

  /**
   * Create test Note data
   */
  createNote(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      content: 'Test text content',
      is_pinned: true,
      author_id: 'Test Author Id',
      ...overrides,
    };
  },

  /**
   * Create test Task data
   */
  createTask(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      title: 'Test Title',
      description: 'Test text content',
      priority: 'Test Priority',
      status: 'Test Status',
      due_date: '2024-01-15',
      completed_at: new Date().toISOString(),
      assigned_to: 'Test Assigned To',
      created_by: 'Test Created By',
      ...overrides,
    };
  },

  /**
   * Create test EmailMessage data
   */
  createEmailMessage(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      contact_id: 'Test Contact Id',
      deal_id: 'Test Deal Id',
      thread_id: 'Test Thread Id',
      subject: 'Test Subject',
      body_text: 'Test text content',
      body_html: 'Test text content',
      direction: 'Test Direction',
      sent_at: new Date().toISOString(),
      received_at: new Date().toISOString(),
      opened_at: new Date().toISOString(),
      open_count: 1,
      ...overrides,
    };
  },

  /**
   * Create test EmailTemplate data
   */
  createEmailTemplate(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: 'Test Name',
      subject: 'Test Subject',
      body_html: 'Test text content',
      body_text: 'Test text content',
      category: 'Test Category',
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Product data
   */
  createProduct(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: 'Test Name',
      sku: 'Test Sku',
      description: 'Test text content',
      unit_price: 10.99,
      currency: 'Test Currency',
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Quote data
   */
  createQuote(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      deal_id: 'Test Deal Id',
      quote_number: 'Test Quote Number',
      status: 'Test Status',
      valid_until: '2024-01-15',
      subtotal: 10.99,
      discount_amount: 10.99,
      tax_amount: 10.99,
      total_amount: 10.99,
      terms: 'Test text content',
      notes: 'Test text content',
      ...overrides,
    };
  },

  /**
   * Create test QuoteItem data
   */
  createQuoteItem(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      quote_id: 'Test Quote Id',
      product_id: 'Test Product Id',
      description: 'Test Description',
      quantity: 1,
      unit_price: 10.99,
      discount_percent: 10.99,
      total_price: 10.99,
      ...overrides,
    };
  },

  /**
   * Create test User data
   */
  createUser(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      email: 'Test Email',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      role: 'Test Role',
      team_id: 'Test Team Id',
      is_active: true,
      last_login: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test Team data
   */
  createTeam(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: 'Test Name',
      manager_id: 'Test Manager Id',
      ...overrides,
    };
  },

};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  await db('bus_company').del();
  await db('bus_contact').del();
  await db('bus_deal').del();
  await db('bus_deal_stage').del();
  await db('bus_pipeline').del();
  await db('bus_activity').del();
  await db('bus_note').del();
  await db('bus_task').del();
  await db('bus_email_message').del();
  await db('bus_email_template').del();
  await db('bus_product').del();
  await db('bus_quote').del();
  await db('bus_quote_item').del();
  await db('bus_user').del();
  await db('bus_team').del();
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
  const db = await initTestDatabase();
  await db.seed.run();
}
