import { promises as fs } from "fs";
import * as path from "path";

import { ErpClawClient } from "./client";
import type { Catalog, CatalogAction } from "./contract";

const PACKAGE_IMPORT_SPECIFIER = "@erdwithai/erpclaw-client";

const GENERATED_FILE_BANNER =
  "// This file is generated by @erdwithai/erpclaw-client's codegen CLI (erpclaw-codegen).\n" +
  "// Do not edit by hand — regenerate it against a live gateway instead.\n";

const OPTIONAL_TYPES_NOTE =
  "// erpclaw enforces required-ness at runtime, not at the type level: every\n" +
  "// field below is optional here even though the underlying action may\n" +
  "// require it. A missing required field surfaces as a 422 at call time,\n" +
  "// not as a TypeScript error. See input_schema.description on the catalog\n" +
  "// entry (or the package README) for details.\n";

/** JSON-Schema primitive type name -> TypeScript type. Unknown types fall back to `unknown`. */
export function jsonSchemaTypeToTs(jsonType: string): string {
  switch (jsonType) {
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "integer":
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

/** "create-sales-invoice" -> "createSalesInvoice". Also used for domain names, e.g. "accounting-adv" -> "accountingAdv". */
export function kebabToCamel(kebab: string): string {
  return kebab
    .split("-")
    .filter((part) => part.length > 0)
    .map((part, i) => (i === 0 ? part : part[0]!.toUpperCase() + part.slice(1)))
    .join("");
}

/** "create-sales-invoice" -> "CreateSalesInvoice". Used for generated type names. */
export function kebabToPascal(kebab: string): string {
  const camel = kebabToCamel(kebab);
  return camel.length > 0 ? camel[0]!.toUpperCase() + camel.slice(1) : camel;
}

function sanitizeComment(text: string): string {
  return text.replace(/\*\//g, "*\\/").replace(/\r?\n/g, " ").trim();
}

function renderArgsInterface(action: CatalogAction): string {
  const typeName = `${kebabToPascal(action.name)}Args`;
  const props = Object.entries(action.input_schema.properties);
  if (props.length === 0) {
    return `export type ${typeName} = Record<string, never>;\n`;
  }
  const fields = props
    .map(([propName, prop]) => {
      const tsType = jsonSchemaTypeToTs(prop.type);
      const comment = prop.description ? `  /** ${sanitizeComment(prop.description)} */\n` : "";
      return `${comment}  ${propName}?: ${tsType};`;
    })
    .join("\n");
  return `export interface ${typeName} {\n${fields}\n}\n`;
}

function renderActionFunction(action: CatalogAction): string {
  const fnName = kebabToCamel(action.name);
  const argsType = `${kebabToPascal(action.name)}Args`;
  const jsdoc = [
    "/**",
    ` * ${sanitizeComment(action.description || action.name)}`.trimEnd(),
    ` * Kind: ${action.kind}${action.destructive ? " (destructive — requires user_confirmed: true, or catch ErpConfirmationRequiredError)" : ""}`,
    " */",
  ].join("\n");
  return (
    `${jsdoc}\n` +
    `export function ${fnName}<TData = Record<string, unknown>>(\n` +
    `  client: ErpClawClient,\n` +
    `  args: ${argsType} = {},\n` +
    `  opts?: { userConfirmed?: boolean },\n` +
    `): Promise<TData> {\n` +
    `  return client.execute<TData>(${JSON.stringify(action.domain)}, ${JSON.stringify(action.name)}, args as Record<string, unknown>, opts);\n` +
    `}\n`
  );
}

function renderDomainBinderFunction(domainName: string, actions: CatalogAction[]): string {
  const binderName = `${kebabToCamel(domainName)}Actions`;
  const entries = actions
    .map((action) => {
      const fnName = kebabToCamel(action.name);
      const argsType = `${kebabToPascal(action.name)}Args`;
      return (
        `    ${fnName}: <TData = Record<string, unknown>>(args?: ${argsType}, opts?: { userConfirmed?: boolean }) =>\n` +
        `      ${fnName}<TData>(client, args, opts),`
      );
    })
    .join("\n");
  return (
    `export function ${binderName}(client: ErpClawClient) {\n` +
    `  return {\n${entries}\n  };\n` +
    `}\n`
  );
}

/** Renders the full `generated/<domain>.ts` module source for one domain's actions. */
export function renderDomainModule(domainName: string, actions: CatalogAction[]): string {
  const sorted = [...actions].sort((a, b) => a.name.localeCompare(b.name));
  const parts = [
    GENERATED_FILE_BANNER,
    OPTIONAL_TYPES_NOTE,
    `import type { ErpClawClient } from ${JSON.stringify(PACKAGE_IMPORT_SPECIFIER)};`,
    "",
    ...sorted.map(renderArgsInterface),
    ...sorted.map(renderActionFunction),
    renderDomainBinderFunction(domainName, sorted),
  ];
  return parts.join("\n");
}

/** Renders `generated/index.ts`, re-exporting every domain module and providing `buildSdk()`. */
export function renderIndexModule(catalog: Catalog): string {
  const domainNames = [...new Set(catalog.actions.map((a) => a.domain))].sort();
  const reExports = domainNames.map((d) => `export * from "./${d}";`).join("\n");
  const imports = domainNames
    .map((d) => `import { ${kebabToCamel(d)}Actions } from "./${d}";`)
    .join("\n");
  const sdkEntries = domainNames.map((d) => `    ${kebabToCamel(d)}: ${kebabToCamel(d)}Actions(client),`).join("\n");

  return [
    GENERATED_FILE_BANNER,
    `import type { ErpClawClient } from ${JSON.stringify(PACKAGE_IMPORT_SPECIFIER)};`,
    imports,
    "",
    reExports,
    "",
    "/** Binds every generated domain's actions to a client, keyed by camelCased domain name. */",
    "export function buildSdk(client: ErpClawClient) {",
    "  return {",
    sdkEntries,
    "  };",
    "}",
    "",
  ].join("\n");
}

export interface CodegenOptions {
  baseUrl: string;
  token: string;
  /** Output directory for generated files. Default: "src/generated" (relative to cwd). */
  outDir?: string;
  fetchImpl?: typeof fetch;
}

export interface CodegenResult {
  outDir: string;
  files: string[];
  catalog: Catalog;
}

/**
 * Fetches a live gateway's catalog and writes one `generated/<domain>.ts`
 * file per domain plus a `generated/index.ts` barrel. Requires a reachable
 * gateway (see the package README) — this function is not exercised against
 * a live server by this package's own test suite.
 */
export async function generate(options: CodegenOptions): Promise<CodegenResult> {
  const outDir = path.resolve(options.outDir ?? path.join("src", "generated"));
  const client = new ErpClawClient({
    baseUrl: options.baseUrl,
    getToken: () => options.token,
    fetchImpl: options.fetchImpl,
  });
  const catalog = await client.catalog(true);

  await fs.mkdir(outDir, { recursive: true });

  const domainNames = [...new Set(catalog.actions.map((a) => a.domain))].sort();
  const files: string[] = [];

  for (const domainName of domainNames) {
    const actions = catalog.actions.filter((a) => a.domain === domainName);
    const filePath = path.join(outDir, `${domainName}.ts`);
    await fs.writeFile(filePath, renderDomainModule(domainName, actions), "utf8");
    files.push(filePath);
  }

  const indexPath = path.join(outDir, "index.ts");
  await fs.writeFile(indexPath, renderIndexModule(catalog), "utf8");
  files.push(indexPath);

  return { outDir, files, catalog };
}
