/**
 *  CRUD Journey Tests
 * Generated by ERDwithAI
 *
 * Complete Create, Read, Update, Delete tests for 
 */

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/App",
    "./pages/List",
    "./pages/Detail"
], function (opaTest) {
    "use strict";

    return {
        run: function () {
            QUnit.module(" CRUD Operations");

            // ========================================
            // CREATE Tests
            // ========================================

            opaTest("Should open create form for ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iPressCreate();

                Then.onTheDetailPage.iShouldSeeTheDetailView();

                Then.iTeardownMyApp();
            });

            opaTest("Should create new  with valid data", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iPressCreate();

                // Fill form fields

                When.onTheDetailPage.iPressSave();

                Then.onTheDetailPage.iShouldSeeSuccessMessage();
                Then.onTheListPage.iShouldSeeAtLeastOneItem();

                Then.iTeardownMyApp();
            });

            opaTest("Should validate required fields on create", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iPressCreate();

                // Try to save without filling required fields
                When.onTheDetailPage.iPressSave();

                // Should show validation errors for required fields

                Then.iTeardownMyApp();
            });

            opaTest("Should cancel create and return to list", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iPressCreate();
                When.onTheDetailPage.iPressCancel();

                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });

            // ========================================
            // READ Tests
            // ========================================

            opaTest("Should display  list", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");

                Then.onTheListPage.iShouldSeeTheList();
                Then.onTheListPage.iShouldSeeCreateButton();

                Then.iTeardownMyApp();
            });

            opaTest("Should display  details", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);

                Then.onTheDetailPage.iShouldSeeTheDetailView();

                Then.iTeardownMyApp();
            });

            opaTest("Should search ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSearchFor("test");

                Then.onTheListPage.iShouldSeeSearchResults("test");

                Then.iTeardownMyApp();
            });

            opaTest("Should clear search and show all ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSearchFor("test");
                When.onTheListPage.iClearSearch();

                Then.onTheListPage.iShouldSeeAtLeastOneItem();

                Then.iTeardownMyApp();
            });

            opaTest("Should refresh  list", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iPressRefresh();

                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });

            // ========================================
            // UPDATE Tests
            // ========================================

            opaTest("Should enter edit mode for ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressEdit();


                Then.iTeardownMyApp();
            });

            opaTest("Should update  successfully", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressEdit();

                // Update a field

                When.onTheDetailPage.iPressSave();

                Then.onTheDetailPage.iShouldSeeSuccessMessage();

                Then.iTeardownMyApp();
            });

            opaTest("Should validate updates on ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressEdit();

                // Clear a required field

                When.onTheDetailPage.iPressSave();

                // Should show validation error

                Then.iTeardownMyApp();
            });

            opaTest("Should cancel update and revert changes", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressEdit();

                // Make changes

                When.onTheDetailPage.iPressCancel();

                // Changes should be reverted
                Then.onTheDetailPage.iShouldSeeTheDetailView();

                Then.iTeardownMyApp();
            });

            // ========================================
            // DELETE Tests
            // ========================================

            opaTest("Should show delete confirmation for ", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressDelete();

                Then.onTheDetailPage.iShouldSeeDeleteConfirmation();

                Then.iTeardownMyApp();
            });

            opaTest("Should cancel delete operation", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressDelete();
                When.onTheDetailPage.iCancelDelete();

                Then.onTheDetailPage.iShouldSeeTheDetailView();

                Then.iTeardownMyApp();
            });

            opaTest("Should delete  successfully", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressDelete();
                When.onTheDetailPage.iConfirmDelete();

                Then.onTheDetailPage.iShouldSeeSuccessMessage();
                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });
        }
    };
});
