/**
 * Navigation Journey Tests for QA Test Project
 * Generated by ERDwithAI
 */

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/App",
    "./pages/List",
    "./pages/Detail"
], function (opaTest) {
    "use strict";

    return {
        run: function () {
            QUnit.module("Navigation");

            opaTest("Should see the app", function (Given, When, Then) {
                // Arrangements
                Given.iStartMyApp();

                // Assertions
                Then.onTheAppPage.iShouldSeeTheApp();

                // Cleanup
                Then.iTeardownMyApp();
            });

            opaTest("Should navigate to list view", function (Given, When, Then) {
                Given.iStartMyApp();

                // Navigate to first entity
                When.onTheAppPage.iNavigateToEntity("USERS");
                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });

            opaTest("Should navigate from list to detail", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("USERS");
                When.onTheListPage.iSelectItem(0);
                Then.onTheDetailPage.iShouldSeeTheDetailView();

                Then.iTeardownMyApp();
            });

            opaTest("Should navigate back from detail to list", function (Given, When, Then) {
                Given.iStartMyApp();

                When.onTheAppPage.iNavigateToEntity("USERS");
                When.onTheListPage.iSelectItem(0);
                When.onTheDetailPage.iPressBack();
                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });

            opaTest("Should handle deep linking", function (Given, When, Then) {
                Given.iStartMyAppWithHash("#/bus-users");
                Then.onTheListPage.iShouldSeeTheList();

                Then.iTeardownMyApp();
            });
        }
    };
});
