/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as BususerIndexImport } from './routes/bus_user/index'
import { Route as BusteamIndexImport } from './routes/bus_team/index'
import { Route as BustaskIndexImport } from './routes/bus_task/index'
import { Route as BusquoteitemIndexImport } from './routes/bus_quote_item/index'
import { Route as BusquoteIndexImport } from './routes/bus_quote/index'
import { Route as BusproductIndexImport } from './routes/bus_product/index'
import { Route as BuspipelineIndexImport } from './routes/bus_pipeline/index'
import { Route as BusnoteIndexImport } from './routes/bus_note/index'
import { Route as BusemailtemplateIndexImport } from './routes/bus_email_template/index'
import { Route as BusemailmessageIndexImport } from './routes/bus_email_message/index'
import { Route as BusdealstageIndexImport } from './routes/bus_deal_stage/index'
import { Route as BusdealIndexImport } from './routes/bus_deal/index'
import { Route as BuscontactIndexImport } from './routes/bus_contact/index'
import { Route as BuscompanyIndexImport } from './routes/bus_company/index'
import { Route as BusactivityIndexImport } from './routes/bus_activity/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as BususerIdImport } from './routes/bus_user/$id'
import { Route as BusteamIdImport } from './routes/bus_team/$id'
import { Route as BustaskIdImport } from './routes/bus_task/$id'
import { Route as BusquoteitemIdImport } from './routes/bus_quote_item/$id'
import { Route as BusquoteIdImport } from './routes/bus_quote/$id'
import { Route as BusproductIdImport } from './routes/bus_product/$id'
import { Route as BuspipelineIdImport } from './routes/bus_pipeline/$id'
import { Route as BusnoteIdImport } from './routes/bus_note/$id'
import { Route as BusemailtemplateIdImport } from './routes/bus_email_template/$id'
import { Route as BusemailmessageIdImport } from './routes/bus_email_message/$id'
import { Route as BusdealstageIdImport } from './routes/bus_deal_stage/$id'
import { Route as BusdealIdImport } from './routes/bus_deal/$id'
import { Route as BuscontactIdImport } from './routes/bus_contact/$id'
import { Route as BuscompanyIdImport } from './routes/bus_company/$id'
import { Route as BusactivityIdImport } from './routes/bus_activity/$id'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminWorkflowsImport } from './routes/admin/workflows'
import { Route as AdminRulesImport } from './routes/admin/rules'
import { Route as AdminFieldsImport } from './routes/admin/fields'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BususerIndexRoute = BususerIndexImport.update({
  id: '/bus_user/',
  path: '/bus_user/',
  getParentRoute: () => rootRoute,
} as any)

const BusteamIndexRoute = BusteamIndexImport.update({
  id: '/bus_team/',
  path: '/bus_team/',
  getParentRoute: () => rootRoute,
} as any)

const BustaskIndexRoute = BustaskIndexImport.update({
  id: '/bus_task/',
  path: '/bus_task/',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteitemIndexRoute = BusquoteitemIndexImport.update({
  id: '/bus_quote_item/',
  path: '/bus_quote_item/',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteIndexRoute = BusquoteIndexImport.update({
  id: '/bus_quote/',
  path: '/bus_quote/',
  getParentRoute: () => rootRoute,
} as any)

const BusproductIndexRoute = BusproductIndexImport.update({
  id: '/bus_product/',
  path: '/bus_product/',
  getParentRoute: () => rootRoute,
} as any)

const BuspipelineIndexRoute = BuspipelineIndexImport.update({
  id: '/bus_pipeline/',
  path: '/bus_pipeline/',
  getParentRoute: () => rootRoute,
} as any)

const BusnoteIndexRoute = BusnoteIndexImport.update({
  id: '/bus_note/',
  path: '/bus_note/',
  getParentRoute: () => rootRoute,
} as any)

const BusemailtemplateIndexRoute = BusemailtemplateIndexImport.update({
  id: '/bus_email_template/',
  path: '/bus_email_template/',
  getParentRoute: () => rootRoute,
} as any)

const BusemailmessageIndexRoute = BusemailmessageIndexImport.update({
  id: '/bus_email_message/',
  path: '/bus_email_message/',
  getParentRoute: () => rootRoute,
} as any)

const BusdealstageIndexRoute = BusdealstageIndexImport.update({
  id: '/bus_deal_stage/',
  path: '/bus_deal_stage/',
  getParentRoute: () => rootRoute,
} as any)

const BusdealIndexRoute = BusdealIndexImport.update({
  id: '/bus_deal/',
  path: '/bus_deal/',
  getParentRoute: () => rootRoute,
} as any)

const BuscontactIndexRoute = BuscontactIndexImport.update({
  id: '/bus_contact/',
  path: '/bus_contact/',
  getParentRoute: () => rootRoute,
} as any)

const BuscompanyIndexRoute = BuscompanyIndexImport.update({
  id: '/bus_company/',
  path: '/bus_company/',
  getParentRoute: () => rootRoute,
} as any)

const BusactivityIndexRoute = BusactivityIndexImport.update({
  id: '/bus_activity/',
  path: '/bus_activity/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const BususerIdRoute = BususerIdImport.update({
  id: '/bus_user/$id',
  path: '/bus_user/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusteamIdRoute = BusteamIdImport.update({
  id: '/bus_team/$id',
  path: '/bus_team/$id',
  getParentRoute: () => rootRoute,
} as any)

const BustaskIdRoute = BustaskIdImport.update({
  id: '/bus_task/$id',
  path: '/bus_task/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteitemIdRoute = BusquoteitemIdImport.update({
  id: '/bus_quote_item/$id',
  path: '/bus_quote_item/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteIdRoute = BusquoteIdImport.update({
  id: '/bus_quote/$id',
  path: '/bus_quote/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusproductIdRoute = BusproductIdImport.update({
  id: '/bus_product/$id',
  path: '/bus_product/$id',
  getParentRoute: () => rootRoute,
} as any)

const BuspipelineIdRoute = BuspipelineIdImport.update({
  id: '/bus_pipeline/$id',
  path: '/bus_pipeline/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusnoteIdRoute = BusnoteIdImport.update({
  id: '/bus_note/$id',
  path: '/bus_note/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusemailtemplateIdRoute = BusemailtemplateIdImport.update({
  id: '/bus_email_template/$id',
  path: '/bus_email_template/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusemailmessageIdRoute = BusemailmessageIdImport.update({
  id: '/bus_email_message/$id',
  path: '/bus_email_message/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusdealstageIdRoute = BusdealstageIdImport.update({
  id: '/bus_deal_stage/$id',
  path: '/bus_deal_stage/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusdealIdRoute = BusdealIdImport.update({
  id: '/bus_deal/$id',
  path: '/bus_deal/$id',
  getParentRoute: () => rootRoute,
} as any)

const BuscontactIdRoute = BuscontactIdImport.update({
  id: '/bus_contact/$id',
  path: '/bus_contact/$id',
  getParentRoute: () => rootRoute,
} as any)

const BuscompanyIdRoute = BuscompanyIdImport.update({
  id: '/bus_company/$id',
  path: '/bus_company/$id',
  getParentRoute: () => rootRoute,
} as any)

const BusactivityIdRoute = BusactivityIdImport.update({
  id: '/bus_activity/$id',
  path: '/bus_activity/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminWorkflowsRoute = AdminWorkflowsImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => rootRoute,
} as any)

const AdminRulesRoute = AdminRulesImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRoute,
} as any)

const AdminFieldsRoute = AdminFieldsImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsImport
      parentRoute: typeof rootRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesImport
      parentRoute: typeof rootRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/bus_activity/$id': {
      id: '/bus_activity/$id'
      path: '/bus_activity/$id'
      fullPath: '/bus_activity/$id'
      preLoaderRoute: typeof BusactivityIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_company/$id': {
      id: '/bus_company/$id'
      path: '/bus_company/$id'
      fullPath: '/bus_company/$id'
      preLoaderRoute: typeof BuscompanyIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_contact/$id': {
      id: '/bus_contact/$id'
      path: '/bus_contact/$id'
      fullPath: '/bus_contact/$id'
      preLoaderRoute: typeof BuscontactIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal/$id': {
      id: '/bus_deal/$id'
      path: '/bus_deal/$id'
      fullPath: '/bus_deal/$id'
      preLoaderRoute: typeof BusdealIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal_stage/$id': {
      id: '/bus_deal_stage/$id'
      path: '/bus_deal_stage/$id'
      fullPath: '/bus_deal_stage/$id'
      preLoaderRoute: typeof BusdealstageIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_message/$id': {
      id: '/bus_email_message/$id'
      path: '/bus_email_message/$id'
      fullPath: '/bus_email_message/$id'
      preLoaderRoute: typeof BusemailmessageIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_template/$id': {
      id: '/bus_email_template/$id'
      path: '/bus_email_template/$id'
      fullPath: '/bus_email_template/$id'
      preLoaderRoute: typeof BusemailtemplateIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_note/$id': {
      id: '/bus_note/$id'
      path: '/bus_note/$id'
      fullPath: '/bus_note/$id'
      preLoaderRoute: typeof BusnoteIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_pipeline/$id': {
      id: '/bus_pipeline/$id'
      path: '/bus_pipeline/$id'
      fullPath: '/bus_pipeline/$id'
      preLoaderRoute: typeof BuspipelineIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_product/$id': {
      id: '/bus_product/$id'
      path: '/bus_product/$id'
      fullPath: '/bus_product/$id'
      preLoaderRoute: typeof BusproductIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote/$id': {
      id: '/bus_quote/$id'
      path: '/bus_quote/$id'
      fullPath: '/bus_quote/$id'
      preLoaderRoute: typeof BusquoteIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote_item/$id': {
      id: '/bus_quote_item/$id'
      path: '/bus_quote_item/$id'
      fullPath: '/bus_quote_item/$id'
      preLoaderRoute: typeof BusquoteitemIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_task/$id': {
      id: '/bus_task/$id'
      path: '/bus_task/$id'
      fullPath: '/bus_task/$id'
      preLoaderRoute: typeof BustaskIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_team/$id': {
      id: '/bus_team/$id'
      path: '/bus_team/$id'
      fullPath: '/bus_team/$id'
      preLoaderRoute: typeof BusteamIdImport
      parentRoute: typeof rootRoute
    }
    '/bus_user/$id': {
      id: '/bus_user/$id'
      path: '/bus_user/$id'
      fullPath: '/bus_user/$id'
      preLoaderRoute: typeof BususerIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_activity/': {
      id: '/bus_activity/'
      path: '/bus_activity'
      fullPath: '/bus_activity'
      preLoaderRoute: typeof BusactivityIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_company/': {
      id: '/bus_company/'
      path: '/bus_company'
      fullPath: '/bus_company'
      preLoaderRoute: typeof BuscompanyIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_contact/': {
      id: '/bus_contact/'
      path: '/bus_contact'
      fullPath: '/bus_contact'
      preLoaderRoute: typeof BuscontactIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal/': {
      id: '/bus_deal/'
      path: '/bus_deal'
      fullPath: '/bus_deal'
      preLoaderRoute: typeof BusdealIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal_stage/': {
      id: '/bus_deal_stage/'
      path: '/bus_deal_stage'
      fullPath: '/bus_deal_stage'
      preLoaderRoute: typeof BusdealstageIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_message/': {
      id: '/bus_email_message/'
      path: '/bus_email_message'
      fullPath: '/bus_email_message'
      preLoaderRoute: typeof BusemailmessageIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_template/': {
      id: '/bus_email_template/'
      path: '/bus_email_template'
      fullPath: '/bus_email_template'
      preLoaderRoute: typeof BusemailtemplateIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_note/': {
      id: '/bus_note/'
      path: '/bus_note'
      fullPath: '/bus_note'
      preLoaderRoute: typeof BusnoteIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_pipeline/': {
      id: '/bus_pipeline/'
      path: '/bus_pipeline'
      fullPath: '/bus_pipeline'
      preLoaderRoute: typeof BuspipelineIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_product/': {
      id: '/bus_product/'
      path: '/bus_product'
      fullPath: '/bus_product'
      preLoaderRoute: typeof BusproductIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote/': {
      id: '/bus_quote/'
      path: '/bus_quote'
      fullPath: '/bus_quote'
      preLoaderRoute: typeof BusquoteIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote_item/': {
      id: '/bus_quote_item/'
      path: '/bus_quote_item'
      fullPath: '/bus_quote_item'
      preLoaderRoute: typeof BusquoteitemIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_task/': {
      id: '/bus_task/'
      path: '/bus_task'
      fullPath: '/bus_task'
      preLoaderRoute: typeof BustaskIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_team/': {
      id: '/bus_team/'
      path: '/bus_team'
      fullPath: '/bus_team'
      preLoaderRoute: typeof BusteamIndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_user/': {
      id: '/bus_user/'
      path: '/bus_user'
      fullPath: '/bus_user'
      preLoaderRoute: typeof BususerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin': typeof AdminIndexRoute
  '/bus_activity': typeof BusactivityIndexRoute
  '/bus_company': typeof BuscompanyIndexRoute
  '/bus_contact': typeof BuscontactIndexRoute
  '/bus_deal': typeof BusdealIndexRoute
  '/bus_deal_stage': typeof BusdealstageIndexRoute
  '/bus_email_message': typeof BusemailmessageIndexRoute
  '/bus_email_template': typeof BusemailtemplateIndexRoute
  '/bus_note': typeof BusnoteIndexRoute
  '/bus_pipeline': typeof BuspipelineIndexRoute
  '/bus_product': typeof BusproductIndexRoute
  '/bus_quote': typeof BusquoteIndexRoute
  '/bus_quote_item': typeof BusquoteitemIndexRoute
  '/bus_task': typeof BustaskIndexRoute
  '/bus_team': typeof BusteamIndexRoute
  '/bus_user': typeof BususerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin': typeof AdminIndexRoute
  '/bus_activity': typeof BusactivityIndexRoute
  '/bus_company': typeof BuscompanyIndexRoute
  '/bus_contact': typeof BuscontactIndexRoute
  '/bus_deal': typeof BusdealIndexRoute
  '/bus_deal_stage': typeof BusdealstageIndexRoute
  '/bus_email_message': typeof BusemailmessageIndexRoute
  '/bus_email_template': typeof BusemailtemplateIndexRoute
  '/bus_note': typeof BusnoteIndexRoute
  '/bus_pipeline': typeof BuspipelineIndexRoute
  '/bus_product': typeof BusproductIndexRoute
  '/bus_quote': typeof BusquoteIndexRoute
  '/bus_quote_item': typeof BusquoteitemIndexRoute
  '/bus_task': typeof BustaskIndexRoute
  '/bus_team': typeof BusteamIndexRoute
  '/bus_user': typeof BususerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bus_activity/': typeof BusactivityIndexRoute
  '/bus_company/': typeof BuscompanyIndexRoute
  '/bus_contact/': typeof BuscontactIndexRoute
  '/bus_deal/': typeof BusdealIndexRoute
  '/bus_deal_stage/': typeof BusdealstageIndexRoute
  '/bus_email_message/': typeof BusemailmessageIndexRoute
  '/bus_email_template/': typeof BusemailtemplateIndexRoute
  '/bus_note/': typeof BusnoteIndexRoute
  '/bus_pipeline/': typeof BuspipelineIndexRoute
  '/bus_product/': typeof BusproductIndexRoute
  '/bus_quote/': typeof BusquoteIndexRoute
  '/bus_quote_item/': typeof BusquoteitemIndexRoute
  '/bus_task/': typeof BustaskIndexRoute
  '/bus_team/': typeof BusteamIndexRoute
  '/bus_user/': typeof BususerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin'
    | '/bus_activity'
    | '/bus_company'
    | '/bus_contact'
    | '/bus_deal'
    | '/bus_deal_stage'
    | '/bus_email_message'
    | '/bus_email_template'
    | '/bus_note'
    | '/bus_pipeline'
    | '/bus_product'
    | '/bus_quote'
    | '/bus_quote_item'
    | '/bus_task'
    | '/bus_team'
    | '/bus_user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin'
    | '/bus_activity'
    | '/bus_company'
    | '/bus_contact'
    | '/bus_deal'
    | '/bus_deal_stage'
    | '/bus_email_message'
    | '/bus_email_template'
    | '/bus_note'
    | '/bus_pipeline'
    | '/bus_product'
    | '/bus_quote'
    | '/bus_quote_item'
    | '/bus_task'
    | '/bus_team'
    | '/bus_user'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin/'
    | '/bus_activity/'
    | '/bus_company/'
    | '/bus_contact/'
    | '/bus_deal/'
    | '/bus_deal_stage/'
    | '/bus_email_message/'
    | '/bus_email_template/'
    | '/bus_note/'
    | '/bus_pipeline/'
    | '/bus_product/'
    | '/bus_quote/'
    | '/bus_quote_item/'
    | '/bus_task/'
    | '/bus_team/'
    | '/bus_user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BusactivityIdRoute: typeof BusactivityIdRoute
  BuscompanyIdRoute: typeof BuscompanyIdRoute
  BuscontactIdRoute: typeof BuscontactIdRoute
  BusdealIdRoute: typeof BusdealIdRoute
  BusdealstageIdRoute: typeof BusdealstageIdRoute
  BusemailmessageIdRoute: typeof BusemailmessageIdRoute
  BusemailtemplateIdRoute: typeof BusemailtemplateIdRoute
  BusnoteIdRoute: typeof BusnoteIdRoute
  BuspipelineIdRoute: typeof BuspipelineIdRoute
  BusproductIdRoute: typeof BusproductIdRoute
  BusquoteIdRoute: typeof BusquoteIdRoute
  BusquoteitemIdRoute: typeof BusquoteitemIdRoute
  BustaskIdRoute: typeof BustaskIdRoute
  BusteamIdRoute: typeof BusteamIdRoute
  BususerIdRoute: typeof BususerIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BusactivityIndexRoute: typeof BusactivityIndexRoute
  BuscompanyIndexRoute: typeof BuscompanyIndexRoute
  BuscontactIndexRoute: typeof BuscontactIndexRoute
  BusdealIndexRoute: typeof BusdealIndexRoute
  BusdealstageIndexRoute: typeof BusdealstageIndexRoute
  BusemailmessageIndexRoute: typeof BusemailmessageIndexRoute
  BusemailtemplateIndexRoute: typeof BusemailtemplateIndexRoute
  BusnoteIndexRoute: typeof BusnoteIndexRoute
  BuspipelineIndexRoute: typeof BuspipelineIndexRoute
  BusproductIndexRoute: typeof BusproductIndexRoute
  BusquoteIndexRoute: typeof BusquoteIndexRoute
  BusquoteitemIndexRoute: typeof BusquoteitemIndexRoute
  BustaskIndexRoute: typeof BustaskIndexRoute
  BusteamIndexRoute: typeof BusteamIndexRoute
  BususerIndexRoute: typeof BususerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AdminFieldsRoute: AdminFieldsRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BusactivityIdRoute: BusactivityIdRoute,
  BuscompanyIdRoute: BuscompanyIdRoute,
  BuscontactIdRoute: BuscontactIdRoute,
  BusdealIdRoute: BusdealIdRoute,
  BusdealstageIdRoute: BusdealstageIdRoute,
  BusemailmessageIdRoute: BusemailmessageIdRoute,
  BusemailtemplateIdRoute: BusemailtemplateIdRoute,
  BusnoteIdRoute: BusnoteIdRoute,
  BuspipelineIdRoute: BuspipelineIdRoute,
  BusproductIdRoute: BusproductIdRoute,
  BusquoteIdRoute: BusquoteIdRoute,
  BusquoteitemIdRoute: BusquoteitemIdRoute,
  BustaskIdRoute: BustaskIdRoute,
  BusteamIdRoute: BusteamIdRoute,
  BususerIdRoute: BususerIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BusactivityIndexRoute: BusactivityIndexRoute,
  BuscompanyIndexRoute: BuscompanyIndexRoute,
  BuscontactIndexRoute: BuscontactIndexRoute,
  BusdealIndexRoute: BusdealIndexRoute,
  BusdealstageIndexRoute: BusdealstageIndexRoute,
  BusemailmessageIndexRoute: BusemailmessageIndexRoute,
  BusemailtemplateIndexRoute: BusemailtemplateIndexRoute,
  BusnoteIndexRoute: BusnoteIndexRoute,
  BuspipelineIndexRoute: BuspipelineIndexRoute,
  BusproductIndexRoute: BusproductIndexRoute,
  BusquoteIndexRoute: BusquoteIndexRoute,
  BusquoteitemIndexRoute: BusquoteitemIndexRoute,
  BustaskIndexRoute: BustaskIndexRoute,
  BusteamIndexRoute: BusteamIndexRoute,
  BususerIndexRoute: BususerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/admin/fields",
        "/admin/rules",
        "/admin/workflows",
        "/auth/login",
        "/auth/signup",
        "/bus_activity/$id",
        "/bus_company/$id",
        "/bus_contact/$id",
        "/bus_deal/$id",
        "/bus_deal_stage/$id",
        "/bus_email_message/$id",
        "/bus_email_template/$id",
        "/bus_note/$id",
        "/bus_pipeline/$id",
        "/bus_product/$id",
        "/bus_quote/$id",
        "/bus_quote_item/$id",
        "/bus_task/$id",
        "/bus_team/$id",
        "/bus_user/$id",
        "/admin/",
        "/bus_activity/",
        "/bus_company/",
        "/bus_contact/",
        "/bus_deal/",
        "/bus_deal_stage/",
        "/bus_email_message/",
        "/bus_email_template/",
        "/bus_note/",
        "/bus_pipeline/",
        "/bus_product/",
        "/bus_quote/",
        "/bus_quote_item/",
        "/bus_task/",
        "/bus_team/",
        "/bus_user/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/admin/fields": {
      "filePath": "admin/fields.tsx"
    },
    "/admin/rules": {
      "filePath": "admin/rules.tsx"
    },
    "/admin/workflows": {
      "filePath": "admin/workflows.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/bus_activity/$id": {
      "filePath": "bus_activity/$id.tsx"
    },
    "/bus_company/$id": {
      "filePath": "bus_company/$id.tsx"
    },
    "/bus_contact/$id": {
      "filePath": "bus_contact/$id.tsx"
    },
    "/bus_deal/$id": {
      "filePath": "bus_deal/$id.tsx"
    },
    "/bus_deal_stage/$id": {
      "filePath": "bus_deal_stage/$id.tsx"
    },
    "/bus_email_message/$id": {
      "filePath": "bus_email_message/$id.tsx"
    },
    "/bus_email_template/$id": {
      "filePath": "bus_email_template/$id.tsx"
    },
    "/bus_note/$id": {
      "filePath": "bus_note/$id.tsx"
    },
    "/bus_pipeline/$id": {
      "filePath": "bus_pipeline/$id.tsx"
    },
    "/bus_product/$id": {
      "filePath": "bus_product/$id.tsx"
    },
    "/bus_quote/$id": {
      "filePath": "bus_quote/$id.tsx"
    },
    "/bus_quote_item/$id": {
      "filePath": "bus_quote_item/$id.tsx"
    },
    "/bus_task/$id": {
      "filePath": "bus_task/$id.tsx"
    },
    "/bus_team/$id": {
      "filePath": "bus_team/$id.tsx"
    },
    "/bus_user/$id": {
      "filePath": "bus_user/$id.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/bus_activity/": {
      "filePath": "bus_activity/index.tsx"
    },
    "/bus_company/": {
      "filePath": "bus_company/index.tsx"
    },
    "/bus_contact/": {
      "filePath": "bus_contact/index.tsx"
    },
    "/bus_deal/": {
      "filePath": "bus_deal/index.tsx"
    },
    "/bus_deal_stage/": {
      "filePath": "bus_deal_stage/index.tsx"
    },
    "/bus_email_message/": {
      "filePath": "bus_email_message/index.tsx"
    },
    "/bus_email_template/": {
      "filePath": "bus_email_template/index.tsx"
    },
    "/bus_note/": {
      "filePath": "bus_note/index.tsx"
    },
    "/bus_pipeline/": {
      "filePath": "bus_pipeline/index.tsx"
    },
    "/bus_product/": {
      "filePath": "bus_product/index.tsx"
    },
    "/bus_quote/": {
      "filePath": "bus_quote/index.tsx"
    },
    "/bus_quote_item/": {
      "filePath": "bus_quote_item/index.tsx"
    },
    "/bus_task/": {
      "filePath": "bus_task/index.tsx"
    },
    "/bus_team/": {
      "filePath": "bus_team/index.tsx"
    },
    "/bus_user/": {
      "filePath": "bus_user/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
