import { NextRequest, NextResponse } from "next/server";
import { join } from "path";
import { writeFile, mkdir } from "fs/promises";

const GENERATED_HOOKS_BASE_PATH = join(
  process.cwd(),
  "generated-projects"
);

/**
 * Generate TypeScript code for a single hook
 */
function generateHookCode(hook: { type: string; name: string; entity: string; code: string }, _entityName: string): string {
  const { type, name, entity, code } = hook;

  // Generate the hook function code
  let hookCode = `/**
 * ${type} Hook: ${name}
 *
 * Hook Type: ${type}
 * Entity: ${entity}
 *
 * This hook is executed ${type.startsWith("before") ? "before" : type.startsWith("after") ? "after" : "during"} ${entity} entity operation.
 *
 * @generated by Hook Code Generator
 */

`;

  // Generate function signature based on hook type
  const paramName = type.startsWith("before") ? "data" : "result";

  if (type.startsWith("before")) {
    hookCode += `export async function ${name}${entity}(
  ${paramName}: any
): Promise<any> {
  console.log('[${type}:${name}]', { entity: '${entity}' });

`;
  } else if (type.startsWith("after")) {
    hookCode += `export async function ${name}${entity}(
  ${paramName}: any
): Promise<void> {
  console.log('[${type}:${name}]', { entity: '${entity}' });

`;
  } else if (type === "customValidate") {
    hookCode += `export async function ${name}${entity}(
  data: any
): Promise<{ valid: boolean; errors?: string[] }> {
  console.log('[${type}:${name}]', { entity: '${entity}' });

`;
  }

  // Add the user's code or default implementation
  if (code && code.trim()) {
    // Indent the user's code
    const indentedCode = code
      .split("\n")
      .map((line: string) => "  " + line)
      .join("\n");
    hookCode += indentedCode + "\n";
  } else {
    hookCode += `  // TODO: Implement ${name} logic for ${entity}
  // Your code here

`;
  }

  // Add return statement
  if (type.startsWith("before")) {
    hookCode += `  return ${paramName};
`;
  } else if (type === "customValidate") {
    hookCode += `  return {
    valid: true,
  };
`;
  }

  hookCode += `}\n`;

  return hookCode;
}

/**
 * POST /api/projects/[id]/workflows/[serviceName]/generate
 *
 * Generates TypeScript hook files and saves them to the file system
 */
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string; serviceName: string } }
) {
  try {
    const projectId = params.id;
    const serviceName = params.serviceName;

    const body = await request.json();
    const { hooks } = body;

    if (!hooks || !Array.isArray(hooks) || hooks.length === 0) {
      return NextResponse.json(
        {
          success: false,
          error: "No hooks found to generate code",
        },
        { status: 400 }
      );
    }

    const entityName = serviceName.replace("Service", "");
    const hooksDir = join(
      GENERATED_HOOKS_BASE_PATH,
      projectId,
      "src",
      "modules",
      entityName.toLowerCase(),
      "hooks"
    );

    // Ensure directory exists
    await mkdir(hooksDir, { recursive: true });

    // Generate and save each hook file
    const generatedFiles = await Promise.all(
      hooks.map(async (hook: { type: string; name: string; entity: string; code: string }) => {
        const code = generateHookCode(hook, entityName);
        const fileName = `${hook.type}.${hook.name}.ts`;
        const filePath = join(hooksDir, fileName);

        await writeFile(filePath, code, "utf-8");

        return {
          fileName,
          hookType: hook.type,
          hookName: hook.name,
          code,
        };
      })
    );

    // Generate index.ts file that exports all hooks
    let indexCode = `/**
 * Hook Exports for ${entityName}
 *
 * This file exports all hook functions for ${entityName}.
 * Hooks are dynamically loaded at runtime.
 *
 * @generated
 */

`;

    hooks.forEach((hook: { name: string; type: string }) => {
      indexCode += `export { ${hook.name}${entityName} as ${hook.name} } from './${hook.type}.${hook.name}';\n`;
    });

    const indexFilePath = join(hooksDir, "index.ts");
    await writeFile(indexFilePath, indexCode, "utf-8");

    return NextResponse.json({
      success: true,
      files: generatedFiles,
      hooksCount: hooks.length,
      message: `Generated ${hooks.length} hook files`,
    });
  } catch (error) {
    console.error("Code generation error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to generate code",
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/projects/[id]/workflows/[serviceName]/generate
 *
 * Returns metadata about code generation for a service
 */
export async function GET(
  _request: Request,
  { params }: { params: { id: string; serviceName: string } }
) {
  try {
    const serviceName = params.serviceName;
    const entityName = serviceName.replace("Service", "");

    return NextResponse.json({
      success: true,
      serviceName,
      entityName,
      supportedHooks: [
        "beforeCreate",
        "afterCreate",
        "beforeUpdate",
        "afterUpdate",
        "beforeDelete",
        "afterDelete",
        "beforeQuery",
        "afterQuery",
        "customValidate",
        "beforeRead",
        "afterRead",
        "beforeList",
        "afterList",
      ],
      outputFormat: "typescript",
      fileStructure: `${entityName.toLowerCase()}/hooks/{hookType}.{hookName}.ts`,
    });
  } catch (error) {
    console.error("Error getting generation info:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to get generation info",
      },
      { status: 500 }
    );
  }
}
