/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntityIndexRouteImport } from './routes/$entity/index'
import { Route as EntityIdRouteImport } from './routes/$entity/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIndexRoute = EntityIndexRouteImport.update({
  id: '/$entity/',
  path: '/$entity/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/$entity/$id',
  path: '/$entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$entity/$id': typeof EntityIdRoute
  '/$entity/': typeof EntityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$entity/$id': typeof EntityIdRoute
  '/$entity': typeof EntityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$entity/$id': typeof EntityIdRoute
  '/$entity/': typeof EntityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$entity/$id' | '/$entity/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$entity/$id' | '/$entity'
  id: '__root__' | '/' | '/$entity/$id' | '/$entity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntityIdRoute: typeof EntityIdRoute
  EntityIndexRoute: typeof EntityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entity/': {
      id: '/$entity/'
      path: '/$entity'
      fullPath: '/$entity/'
      preLoaderRoute: typeof EntityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entity/$id': {
      id: '/$entity/$id'
      path: '/$entity/$id'
      fullPath: '/$entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntityIdRoute: EntityIdRoute,
  EntityIndexRoute: EntityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
